---
title: "Reading data from the web"
output: github_document
---

```{r, echo = FALSE, message=FALSE}
library(tidyverse)
library(rvest)
library(httr)

```

NSDUH data

```{r}

url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_html = read_html(url)

drug_use_html
```


```{r}

drug_use_df = 
  drug_use_html %>%
  html_table() %>%
  first() %>%
  slice(-1)

drug_use_df
```


CSS Selectors

```{r}

sw_url = "https://www.imdb.com/list/ls070150896/"
sw_html = 
  read_html(sw_url)

sw_html
```


```{r}


sw_titles =
sw_html %>%
  html_elements(".lister-item-header a") %>%
  html_text()

```


```{r}

sw_revenue = 
sw_html %>%
  html_elements(".text-muted .ghost~ .text-muted+ span") %>%
  html_text()

```


```{r}

sw_df =
  tibble(
    title = sw_titles,
    revenue = sw_revenue
  )

sw_df
```


Dynamite reviews

```{r}

dynamite_url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = read_html(dynamite_url)

dynamite_review_titles =
  dynamite_html %>%
  html_elements(".a-text-bold span") %>%
  html_text()

dynamite_review_titles

dynamite_stars = 
  dynamite_html %>%
  html_elements("#cm_cr-review_list .review-rating") %>%
  html_text()


dynamite_stars

```


```{r}

dynamite_df = 
  tibble(
    reviews = dynamite_review_titles,
    rating = dynamite_stars
  )

dynamite_df

```

Using API

NYC water
```{r}

water_df = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") %>%
  content()

water_df
```

json

```{r}

water_json = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.json") %>%
  content("text") %>%
  jsonlite::fromJSON() %>%
  as_tibble()

water_json

```

BRFSS

```{r}

brfss_df = 
  GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv",
      query = list("$limit" = 5000)) %>% 
  content()
  
  # query = list("$limit" = 5000)) %>% 

brfss_df
```

